### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by alex88** [westoque/phantomjs.rb#12]
Running phantomjs within a sidekiq worker using this code:

```
    Phantomjs.inline(js) do |line|
      line.chomp!
      @logger.info line
      if line == 'TIMEOUT'
        @logger.error 'Page timeout, exiting'

        exit = true
      end
    end

```

creates a zombie phantomjs process on each run, is there a way to avoid this?

**Comment by mkorfmann** [comment]
Thanks for the fix, having issues with this as well. :+1:
